/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,ts,tsx,vue,svelte,mdx}"],
  theme: {
    extend: {
      colors: {
        ivory: "#FFFFFF",
        tertiary: "#000000",
        charcoal: "#161616",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e8e8e8",
        "surface-bright": "#f9f9f9",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#251a07",
        "surface-tint": "#5f5e5e",
        "secondary-container": "#f3dcbe",
        surface: "#f9f9f9",
        "on-background": "#1a1c1c",
        "tertiary-fixed-dim": "#ddc2a6",
        "on-tertiary-container": "#978067",
        "secondary-fixed": "#f6dfc1",
        background: "#f9f9f9",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f0f1f1",
        outline: "#747878",
        "on-primary-fixed-variant": "#474746",
        "surface-dim": "#dadada",
        "on-tertiary-fixed": "#271907",
        "on-surface-variant": "#444748",
        error: "#ba1a1a",
        "surface-container-low": "#f3f3f4",
        "outline-variant": "#c4c7c7",
        "on-surface": "#1a1c1c",
        "inverse-surface": "#2f3131",
        "soft-beige": "#F0D9BB",
        "inverse-primary": "#c8c6c5",
        taupe: "#D9C5B2",
        "on-secondary-container": "#716048",
        "tertiary-fixed": "#fadec0",
        "on-secondary": "#ffffff",
        primary: "#000000",
        "on-tertiary-fixed-variant": "#56432e",
        "primary-container": "#1c1b1b",
        secondary: "#6c5c44",
        "secondary-fixed-dim": "#d9c3a6",
        "primary-fixed": "#e5e2e1",
        "on-primary-fixed": "#1c1b1b",
        "warm-brown": "#5E4B3C",
        "on-primary-container": "#858383",
        "on-secondary-fixed-variant": "#53442e",
        "surface-variant": "#e2e2e2",
        "primary-fixed-dim": "#c8c6c5",
        "on-error-container": "#93000a",
        "surface-container": "#eeeeee",
        "surface-container-highest": "#e2e2e2",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#271907",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "grid-margin-mobile": "24px",
        gutter: "24px",
        "section-gap-lg": "160px",
        "section-gap-md": "80px",
        "stack-lg": "32px",
        "grid-margin-desktop": "64px",
        "stack-md": "16px",
      },
      fontFamily: {
        "display-xl": ["EB Garamond", "serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["EB Garamond", "serif"],
        "display-xl-mobile": ["EB Garamond", "serif"],
        "headline-lg-mobile": ["EB Garamond", "serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["EB Garamond", "serif"],
        "label-caps": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "display-xl": [
          "80px",
          { lineHeight: "96px", letterSpacing: "-0.02em", fontWeight: "400" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "400" }],
        "display-xl-mobile": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "400" },
        ],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "40px", fontWeight: "400" },
        ],
        "body-lg": ["18px", { lineHeight: "32px", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "56px", fontWeight: "400" }],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};
